import type { MarketEstimate } from "@/lib/market.functions";
import type { AuctionSale } from "@/lib/types";

// Données fictives destinées à la page publique d'exemple.
export const EXAMPLE_SALE = {
  id: "example-immojudis-bordeaux-t2",
  title: "Appartement T2 avec balcon à Bordeaux",
  description:
    "Appartement de deux pièces avec balcon, situé à Bordeaux, dans un immeuble ancien proche du tribunal.",
  source_description:
    "Appartement de deux pièces avec balcon, situé à Bordeaux, dans un immeuble ancien proche du tribunal.",
  llm_display_description:
    "Appartement de deux pièces situé à Bordeaux, dans un immeuble ancien à proximité du tribunal. Le descriptif d'exemple mentionne un balcon, une surface Carrez de 42,6 m² et un rafraîchissement à prévoir avant remise en location ou revente.",
  about_description:
    "Appartement de deux pièces situé à Bordeaux, dans un immeuble ancien à proximité du tribunal. Le descriptif d'exemple mentionne un balcon, une surface Carrez de 42,6 m² et un rafraîchissement à prévoir avant remise en location ou revente.",
  city: "Bordeaux",
  department: "Gironde",
  postal_code: "33000",
  address: "63 Pl. des Martyrs de la Résistance",
  tribunal: "TJ Bordeaux",
  tribunal_code: "tj-bordeaux",
  tribunal_name: "Tribunal judiciaire de Bordeaux",
  tribunal_city: "Bordeaux",
  property_type: "apartment",
  starting_price_eur: 92_000,
  sale_date: "2026-10-15T09:30:00+02:00",
  visit_dates: ["2026-10-02 à 14:00", "2026-10-07 à 10:30"],
  lawyer_name: "Me Camille Durand",
  lawyer_contact: "contact-demo@immojudis.fr",
  adjudication_price_eur: null,
  latitude: 44.842748,
  longitude: -0.586227,
  occupancy_status: "unknown",
  habitable_surface_m2: 42.6,
  carrez_surface_m2: 42.6,
  land_surface_m2: null,
  app_surface_m2: 42.6,
  app_surface_kind: "Carrez",
  surface_scope: "lot principal",
  surface_source: "pv_descriptif",
  surface_confidence: 0.91,
  surface_evidence:
    "Le PV descriptif d'exemple mentionne un appartement de deux pièces, surface Carrez 42,6 m², avec balcon donnant sur cour.",
  rooms_count: 2,
  bedrooms_count: 1,
  bathrooms_count: 1,
  parking_count: null,
  has_garden: false,
  has_terrace: true,
  has_garage: false,
  has_pool: false,
  has_air_conditioning: false,
  has_double_glazing: true,
  investment_score: 78,
  investment_summary:
    "Mise à prix basse face au marché local, mais occupation et travaux à vérifier avant audience.",
  score_version: "demo-2026-06",
  score_confidence: 0.84,
  score_factors: [
    {
      factor_order: 1,
      factor_key: "starting_price",
      label: "Mise à prix",
      reason: "La mise à prix reste nettement sous la médiane locale observée.",
      delta: 18,
      confidence: 0.88,
      evidence: "Mise à prix 92 000 EUR pour 42,6 m².",
    },
    {
      factor_order: 2,
      factor_key: "occupation",
      label: "Occupation",
      reason: "L'occupation doit être confirmée dans le PV et le cahier des conditions.",
      delta: -8,
      confidence: 0.72,
      evidence: "Mention d'occupation non stabilisée dans les pièces d'exemple.",
    },
  ],
  risk_notes:
    "Dossier fictif : les risques ci-dessous illustrent les points qu'Immojudis rattache aux pièces.",
  source_name: "Dossier de démonstration Immojudis",
  source_url: "/ressources",
  primary_source: "Annonce d'exemple Immojudis",
  source_urls: ["/ressources"],
  source_blocks: {
    usage: "Habitation",
    ancien_neuf: "Ancien",
    etat: "Rafraîchissement à prévoir",
    nb_etages: "3e étage sur 4",
    dpe_classe: "D",
    consignation: 9_200,
    mode_vente: "Audience d'adjudication",
    seance_paiement: "Frais et consignation selon cahier des conditions",
    auction_location: "Tribunal judiciaire de Bordeaux",
    source_updated_at: "2026-06-20T10:20:00+02:00",
  },
  source_blocks_by_source: {
    "demo:primary": {
      avocat: "Me Camille Durand",
      contact_avocat: "contact-demo@immojudis.fr",
      visites: "2026-10-02 à 14:00 · 2026-10-07 à 10:30",
    },
  },
  dedupe_confidence: "demo",
  quality_flags: [],
  documents: [
    {
      url: "/ressources",
      name: "Cahier des conditions de vente - exemple",
      type: "cahier_conditions_vente",
    },
    {
      url: "/ressources",
      name: "PV descriptif - exemple",
      type: "pv_descriptif",
    },
  ],
  documents_rich: [
    {
      url: "/ressources",
      label: "Cahier des conditions de vente - exemple",
      type: "cahier_conditions_vente",
      document_type: "cahier_conditions_vente",
      extraction_status: "demo",
      download_status: "demo",
      docling_status: "demo",
      text_chars: 18_420,
    },
    {
      url: "/ressources",
      label: "PV descriptif - exemple",
      type: "pv_descriptif",
      document_type: "pv_descriptif",
      extraction_status: "demo",
      download_status: "demo",
      docling_status: "demo",
      text_chars: 9_860,
    },
    {
      url: "/ressources",
      label: "Diagnostics techniques - exemple",
      type: "diagnostics_techniques",
      document_type: "diagnostics_techniques",
      extraction_status: "demo",
      download_status: "demo",
      docling_status: "demo",
      text_chars: 7_240,
    },
  ],
  media: [
    {
      type: "image",
      url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=80",
      source: "Visuel d'exemple",
    },
    {
      type: "image",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
      source: "Visuel d'exemple",
    },
    {
      type: "image",
      url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      source: "Visuel d'exemple",
    },
    {
      type: "image",
      url: "https://images.unsplash.com/photo-1560448075-bb485b067938?auto=format&fit=crop&w=1200&q=80",
      source: "Visuel d'exemple",
    },
  ],
  risks: [
    {
      risk_type: "occupation_to_confirm",
      risk_label: "Occupation à confirmer",
      severity: 2,
      evidence:
        "Le PV descriptif d'exemple signale une présence lors du constat sur place, sans bail annexe au dossier.",
      evidence_json: {
        risk_status: "to_verify",
        reasoning:
          "La situation d'occupation peut modifier le délai de récupération et la valeur exploitable.",
        why_it_matters:
          "Confirmer l'occupation avant audience évite de surestimer la liquidité du bien.",
        document_label: "PV descriptif - exemple",
        document_type: "pv_descriptif",
        page_number: 3,
      },
      confidence: 0.78,
      detector: "demo",
      detector_version: "2026-06",
      score_impact: -8,
      occurrences: [
        {
          document_url: "/ressources",
          document_label: "PV descriptif - exemple",
          document_type: "pv_descriptif",
          page_number: 3,
          excerpt:
            "Présence d'une personne se déclarant occupante ; bail non produit dans les pièces communiquées.",
          confidence: 0.78,
          detector: "demo",
          detector_version: "2026-06",
          matched_terms: ["occupation", "bail non produit"],
          score_impact: -8,
          updated_at: "2026-06-20T10:20:00+02:00",
        },
      ],
    },
    {
      risk_type: "works_budget",
      risk_label: "Travaux à chiffrer",
      severity: 2,
      evidence:
        "Les diagnostics et le PV d'exemple mentionnent des rafraîchissements et une ventilation à vérifier.",
      evidence_json: {
        risk_status: "to_quantify",
        reasoning:
          "Le plafond doit intégrer une enveloppe travaux avant toute stratégie offensive.",
        why_it_matters: "Chaque euro de travaux réduit le montant maximum d'enchère acceptable.",
        document_label: "Diagnostics techniques - exemple",
        document_type: "diagnostics_techniques",
        page_number: 6,
      },
      confidence: 0.73,
      detector: "demo",
      detector_version: "2026-06",
      score_impact: -6,
      occurrences: [
        {
          document_url: "/ressources",
          document_label: "Diagnostics techniques - exemple",
          document_type: "diagnostics_techniques",
          page_number: 6,
          excerpt:
            "Ventilation de la salle d'eau à contrôler ; peintures et sols à reprendre selon constat visuel.",
          confidence: 0.73,
          detector: "demo",
          detector_version: "2026-06",
          matched_terms: ["ventilation", "peintures", "sols"],
          score_impact: -6,
          updated_at: "2026-06-20T10:20:00+02:00",
        },
      ],
    },
  ],
  status: "upcoming",
  created_at: "2026-06-20T10:20:00+02:00",
  updated_at: "2026-06-20T10:20:00+02:00",
} satisfies AuctionSale;

export const EXAMPLE_MARKET_ESTIMATE = {
  source: "DVF Cerema",
  engineVersion: "v2",
  segment: "apartment",
  surfaceBasis: "built",
  actionable: true,
  collectionComplete: true,
  missingYears: [],
  effectiveSampleSize: 8.4,
  estimationLevel: "reliable",
  subjectSurfaceM2: 42.6,
  subjectSurfaceEstimated: false,
  subjectSurfaceAssumption: null,
  subjectSurfaceUncertaintyPct: null,
  locationSource: "provided",
  locationApproximate: false,
  estimatedValueEur: 173_000,
  estimatedValueLowEur: 161_000,
  estimatedValueHighEur: 190_000,
  radiusM: 100,
  yearsBack: 6,
  areaKind: "urban",
  commune: "Bordeaux",
  sampleSize: 12,
  parcelSampleSize: 12,
  totalNearbySampleSize: 38,
  outliersRemoved: 2,
  qualityScore: 84,
  qualityLabel: "forte",
  qualityWarnings: [],
  comparableMode: "surface_matched",
  surfaceMinM2: 32,
  surfaceMaxM2: 58,
  landSurfaceMinM2: null,
  landSurfaceMaxM2: null,
  medianPricePerM2: 4_060,
  p25PricePerM2: 3_780,
  p75PricePerM2: 4_450,
  minPricePerM2: 3_400,
  maxPricePerM2: 5_100,
  deviationPct: null,
  addressHistory: [
    {
      date: "2024-09-12",
      totalPrice: 178_000,
      surface: 43,
      pricePerM2: 4_140,
      type: "Appartement",
    },
  ],
  recentTransactions: [
    {
      date: "2025-11-18",
      pricePerM2: 4_280,
      surface: 41,
      totalPrice: 175_480,
      type: "Appartement",
      distanceM: 84,
    },
    {
      date: "2025-07-04",
      pricePerM2: 3_920,
      surface: 46,
      totalPrice: 180_320,
      type: "Appartement",
      distanceM: 62,
    },
    {
      date: "2024-12-09",
      pricePerM2: 4_510,
      surface: 38,
      totalPrice: 171_380,
      type: "Appartement",
      distanceM: 93,
    },
    {
      date: "2024-05-22",
      pricePerM2: 3_760,
      surface: 54,
      totalPrice: 203_040,
      type: "Appartement",
      distanceM: 71,
    },
  ],
} satisfies MarketEstimate;
