import type { Property } from "@/lib/property-types";

const LOCAL_PHOTOS = [
  "/media/landing/auction-bordeaux.jpg",
  "/media/landing/auction-toulouse.jpg",
  "/media/landing/auction-nantes.jpg",
  "/media/landing/auction-lyon.jpg",
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "bordeaux-premium-t2",
    slug: "appartement-premium-bordeaux-centre",
    title: "Appartement T2 avec balcon - Bordeaux centre",
    price: 178000,
    currency: "EUR",
    address: "63 Place des Martyrs de la Resistance",
    city: "Bordeaux",
    region: "Nouvelle-Aquitaine",
    postalCode: "33000",
    country: "France",
    beds: 1,
    baths: 1,
    sqft: 459,
    lotSize: "Copropriete",
    yearBuilt: 1900,
    propertyType: "Appartement",
    pricePerSqft: 388,
    description:
      "Appartement deux pieces situe dans un immeuble ancien du centre de Bordeaux. La fiche de demonstration presente une surface compacte, un balcon et une adresse proche des services, des transports et du tribunal. Le bien est pense pour illustrer une fiche immobiliere premium Immojudis avec galerie, analyse, carte, historique et contact direct.",
    photos: LOCAL_PHOTOS.map((url, index) => ({
      id: `bordeaux-photo-${index + 1}`,
      url,
      alt:
        index === 0
          ? "Facade urbaine proche du bien a Bordeaux"
          : `Vue immobiliere de demonstration ${index + 1}`,
      width: 1600,
      height: 1067,
    })),
    location: {
      lat: 44.842748,
      lng: -0.586227,
    },
    agent: {
      name: "Camille Durand",
      phone: "+33 5 56 00 00 00",
      email: "contact-demo@immojudis.fr",
      brokerage: "Immojudis Conseil",
      avatarUrl: "/brand/immojudis-mark-transparent.png",
    },
    facts: [
      { label: "Type", value: "Appartement" },
      { label: "Surface", value: "43 m2" },
      { label: "Pieces", value: "2" },
      { label: "Chambre", value: "1" },
      { label: "Exterieur", value: "Balcon" },
      { label: "Occupation", value: "A confirmer" },
    ],
    details: [
      {
        category: "Interieur",
        items: [
          { label: "Sejour", value: "Piece principale lumineuse" },
          { label: "Cuisine", value: "Cuisine separee" },
          { label: "Salle d'eau", value: "1" },
          { label: "Etat", value: "Rafraichissement a prevoir" },
        ],
      },
      {
        category: "Immeuble",
        items: [
          { label: "Construction", value: "Immeuble ancien" },
          { label: "Etage", value: "Intermediaire" },
          { label: "Copropriete", value: "Oui" },
          { label: "Ascenseur", value: "Non renseigne" },
        ],
      },
      {
        category: "Vente",
        items: [
          { label: "Source", value: "Fixture locale Immojudis" },
          { label: "Dossier", value: "Demonstration" },
          { label: "Disponibilite", value: "Sur demande" },
        ],
      },
    ],
    priceHistory: [
      { date: "2026-06-20", event: "Mise en ligne", price: 178000, source: "Fixture locale" },
      { date: "2026-06-24", event: "Mise a jour photos", source: "Immojudis" },
      { date: "2026-07-01", event: "Synthese IA disponible", source: "Pipeline demo" },
    ],
    similarListings: [
      {
        id: "demo-chartrons-t3",
        slug: "t3-chartrons-demo",
        price: 245000,
        currency: "EUR",
        address: "Rue Notre-Dame",
        city: "Bordeaux",
        beds: 2,
        baths: 1,
        sqft: 645,
        photoUrl: "/media/landing/auction-lyon.jpg",
      },
      {
        id: "demo-talence-t2",
        slug: "t2-talence-demo",
        price: 166000,
        currency: "EUR",
        address: "Cours Gambetta",
        city: "Talence",
        beds: 1,
        baths: 1,
        sqft: 430,
        photoUrl: "/media/landing/auction-toulouse.jpg",
      },
      {
        id: "demo-merignac-maison",
        slug: "maison-merignac-demo",
        price: 318000,
        currency: "EUR",
        address: "Avenue de la Marne",
        city: "Merignac",
        beds: 3,
        baths: 2,
        sqft: 1033,
        photoUrl: "/media/landing/auction-nantes.jpg",
      },
    ],
  },
  {
    id: "demo-chartrons-t3",
    slug: "t3-chartrons-demo",
    title: "Appartement T3 - quartier Chartrons",
    price: 245000,
    currency: "EUR",
    address: "Rue Notre-Dame",
    city: "Bordeaux",
    region: "Nouvelle-Aquitaine",
    postalCode: "33000",
    country: "France",
    beds: 2,
    baths: 1,
    sqft: 645,
    lotSize: "Copropriete",
    yearBuilt: 1930,
    propertyType: "Appartement",
    pricePerSqft: 380,
    description:
      "Appartement de demonstration situe dans le secteur des Chartrons. La fiche illustre un bien comparable avec deux chambres, une surface familiale compacte et une adresse proche des commerces de quartier.",
    photos: [LOCAL_PHOTOS[0], LOCAL_PHOTOS[2], LOCAL_PHOTOS[3]].map((url, index) => ({
      id: `chartrons-photo-${index + 1}`,
      url,
      alt: `Vue de demonstration du bien Chartrons ${index + 1}`,
      width: 1600,
      height: 1067,
    })),
    location: {
      lat: 44.85348,
      lng: -0.57197,
    },
    agent: {
      name: "Camille Durand",
      phone: "+33 5 56 00 00 00",
      email: "contact-demo@immojudis.fr",
      brokerage: "Immojudis Conseil",
      avatarUrl: "/brand/immojudis-mark-transparent.png",
    },
    facts: [
      { label: "Type", value: "Appartement" },
      { label: "Surface", value: "60 m2" },
      { label: "Pieces", value: "3" },
      { label: "Chambres", value: "2" },
    ],
    details: [
      {
        category: "Interieur",
        items: [
          { label: "Sejour", value: "Piece de vie traversante" },
          { label: "Chambres", value: "2" },
          { label: "Salle d'eau", value: "1" },
        ],
      },
      {
        category: "Vente",
        items: [
          { label: "Source", value: "Fixture locale Immojudis" },
          { label: "Dossier", value: "Demonstration" },
        ],
      },
    ],
    priceHistory: [{ date: "2026-06-18", event: "Mise en ligne", price: 245000 }],
    similarListings: [],
  },
  {
    id: "demo-talence-t2",
    slug: "t2-talence-demo",
    title: "Appartement T2 - centre de Talence",
    price: 166000,
    currency: "EUR",
    address: "Cours Gambetta",
    city: "Talence",
    region: "Nouvelle-Aquitaine",
    postalCode: "33400",
    country: "France",
    beds: 1,
    baths: 1,
    sqft: 430,
    lotSize: "Copropriete",
    yearBuilt: 1975,
    propertyType: "Appartement",
    pricePerSqft: 386,
    description:
      "Appartement de demonstration proche du centre de Talence. Le bien met en avant une configuration simple, adaptee a un premier achat ou a un investissement locatif de proximite.",
    photos: [LOCAL_PHOTOS[1], LOCAL_PHOTOS[0], LOCAL_PHOTOS[3]].map((url, index) => ({
      id: `talence-photo-${index + 1}`,
      url,
      alt: `Vue de demonstration du bien Talence ${index + 1}`,
      width: 1600,
      height: 1067,
    })),
    location: {
      lat: 44.81235,
      lng: -0.58922,
    },
    agent: {
      name: "Camille Durand",
      phone: "+33 5 56 00 00 00",
      email: "contact-demo@immojudis.fr",
      brokerage: "Immojudis Conseil",
      avatarUrl: "/brand/immojudis-mark-transparent.png",
    },
    facts: [
      { label: "Type", value: "Appartement" },
      { label: "Surface", value: "40 m2" },
      { label: "Pieces", value: "2" },
      { label: "Chambre", value: "1" },
    ],
    details: [
      {
        category: "Interieur",
        items: [
          { label: "Sejour", value: "Piece principale" },
          { label: "Cuisine", value: "Ouverte" },
          { label: "Salle d'eau", value: "1" },
        ],
      },
      {
        category: "Vente",
        items: [
          { label: "Source", value: "Fixture locale Immojudis" },
          { label: "Dossier", value: "Demonstration" },
        ],
      },
    ],
    priceHistory: [{ date: "2026-06-21", event: "Mise en ligne", price: 166000 }],
    similarListings: [],
  },
  {
    id: "demo-merignac-maison",
    slug: "maison-merignac-demo",
    title: "Maison familiale - Merignac",
    price: 318000,
    currency: "EUR",
    address: "Avenue de la Marne",
    city: "Merignac",
    region: "Nouvelle-Aquitaine",
    postalCode: "33700",
    country: "France",
    beds: 3,
    baths: 2,
    sqft: 1033,
    lotSize: "Jardin privatif",
    yearBuilt: 1992,
    propertyType: "Maison",
    pricePerSqft: 308,
    description:
      "Maison de demonstration a Merignac avec trois chambres et jardin privatif. La fiche sert de comparable local pour presenter un bien plus familial dans l'environnement proche de Bordeaux.",
    photos: [LOCAL_PHOTOS[2], LOCAL_PHOTOS[3], LOCAL_PHOTOS[0]].map((url, index) => ({
      id: `merignac-photo-${index + 1}`,
      url,
      alt: `Vue de demonstration du bien Merignac ${index + 1}`,
      width: 1600,
      height: 1067,
    })),
    location: {
      lat: 44.84277,
      lng: -0.64509,
    },
    agent: {
      name: "Camille Durand",
      phone: "+33 5 56 00 00 00",
      email: "contact-demo@immojudis.fr",
      brokerage: "Immojudis Conseil",
      avatarUrl: "/brand/immojudis-mark-transparent.png",
    },
    facts: [
      { label: "Type", value: "Maison" },
      { label: "Surface", value: "96 m2" },
      { label: "Chambres", value: "3" },
      { label: "Terrain", value: "Jardin privatif" },
    ],
    details: [
      {
        category: "Interieur",
        items: [
          { label: "Sejour", value: "Piece familiale" },
          { label: "Chambres", value: "3" },
          { label: "Salles d'eau", value: "2" },
        ],
      },
      {
        category: "Vente",
        items: [
          { label: "Source", value: "Fixture locale Immojudis" },
          { label: "Dossier", value: "Demonstration" },
        ],
      },
    ],
    priceHistory: [{ date: "2026-06-23", event: "Mise en ligne", price: 318000 }],
    similarListings: [],
  },
  {
    id: "demo-property-without-coords",
    slug: "maison-sans-coordonnees-demo",
    title: "Maison familiale de demonstration",
    price: 296000,
    currency: "EUR",
    address: "Adresse communiquee sur demande",
    city: "La Rochelle",
    region: "Nouvelle-Aquitaine",
    postalCode: "17000",
    country: "France",
    beds: 3,
    baths: 2,
    sqft: 1076,
    lotSize: "Jardin privatif",
    yearBuilt: 1988,
    propertyType: "Maison",
    description:
      "Maison de demonstration destinee a tester les etats de repli de la fiche, notamment l'absence de coordonnees cartographiques. Les informations restent servies depuis les fixtures locales.",
    photos: [],
    agent: {
      name: "Equipe Immojudis",
      email: "contact-demo@immojudis.fr",
      brokerage: "Immojudis Conseil",
    },
    facts: [
      { label: "Type", value: "Maison" },
      { label: "Surface", value: "100 m2" },
      { label: "Chambres", value: "3" },
      { label: "Terrain", value: "Jardin privatif" },
    ],
    details: [
      {
        category: "Etat",
        items: [
          { label: "Coordonnees", value: "Non disponibles" },
          { label: "Photos", value: "A completer" },
        ],
      },
    ],
    priceHistory: [{ date: "2026-06-12", event: "Creation fixture", price: 296000 }],
    similarListings: [],
  },
];

export const DEFAULT_PROPERTY = MOCK_PROPERTIES[0];
