// Browser-safe constants shared by client queries and server routes. Keep this module
// free of Supabase client imports so server code never pulls the browser client in.
import { joinColumns } from "@/lib/supabase-select";

export const DETAIL_VIEW = "v_auction_sales_app";

const SALE_LIST_COLUMN_NAMES = [
  "source_checks",
  "source_conflicts",
  "analysis_status",
  "source_presence",
  "sale_procedure",
  "sale_venue_type",
  "sale_legal_framework",
  "sale_verification_status",
  "id",
  "title",
  "description",
  "source_description",
  "llm_display_description",
  "about_description",
  "city",
  "department",
  "postal_code",
  "address",
  "tribunal",
  "tribunal_code",
  "tribunal_name",
  "tribunal_city",
  "property_type",
  "starting_price_eur",
  "sale_date",
  "visit_dates",
  "lawyer_name",
  "lawyer_contact",
  "adjudication_price_eur",
  "latitude",
  "longitude",
  "occupancy_status",
  "surface_m2",
  "habitable_surface_m2",
  "carrez_surface_m2",
  "land_surface_m2",
  "app_surface_m2",
  "app_surface_kind",
  "surface_scope",
  "surface_source",
  "rooms_count",
  "bedrooms_count",
  "bathrooms_count",
  "has_garden",
  "has_terrace",
  "has_garage",
  "has_pool",
  "has_air_conditioning",
  "has_double_glazing",
  "investment_score",
  "score_confidence",
  "surface_confidence",
  "surface_evidence",
  "risks",
  "documents",
  "documents_rich",
  "media",
  "source_name",
  "source_url",
  "primary_source",
  "source_urls",
  "source_blocks",
  "source_blocks_by_source",
  "dedupe_confidence",
  "quality_flags",
  "status",
  "created_at",
  "updated_at",
] as const;

// Littéral typé : le client Supabase infère ainsi les lignes sélectionnées.
export const SALE_LIST_COLUMNS = joinColumns(SALE_LIST_COLUMN_NAMES);
