#!/usr/bin/env bash
# Regenerate the hashed lockfiles used by `pip install --require-hashes`.
#
#   requirements.txt            -> requirements.lock            (pipeline runtime)
#   requirements-dev.txt        -> requirements-dev.lock        (CI: tests, lint, audit)
#   requirements-valuation.txt  -> requirements-valuation.lock  (model training)
#
# The .txt files stay the human-edited, pinned direct dependencies; the .lock
# files pin every transitive dependency with sha256 hashes for CPython 3.12 on
# Linux (the GitHub-hosted runner). Requires uv (`pip install uv`).
#
# Run from services/data-pipeline after changing a requirements*.txt file:
#   bash scripts/compile_locks.sh
# Pass --upgrade to move transitive dependencies to their latest versions.
set -euo pipefail

cd "$(dirname "$0")/.."

for name in requirements requirements-dev requirements-valuation; do
  {
    echo "# Generated by scripts/compile_locks.sh from ${name}.txt; do not edit by hand."
    echo "# Install with: pip install --require-hashes -r ${name}.lock"
    uv pip compile "${name}.txt" \
      --generate-hashes \
      --python-version 3.12 \
      --python-platform x86_64-manylinux_2_28 \
      --no-header \
      "$@"
  } > "${name}.lock.tmp"
  mv "${name}.lock.tmp" "${name}.lock"
  echo "wrote ${name}.lock"
done
