"""Column lists and select projections for the sale tables."""

from __future__ import annotations

POSTGRES_JSON_COLUMNS = {
    "source_urls",
    "visit_dates",
    "documents",
    "score_factors",
    "premium_readiness_factors",
    "premium_readiness_blockers",
    "premium_readiness_missing_fields",
    "quality_flags",
    "raw_payload",
    "observations",
    "sale_procedure",
}


UPSERT_COLUMNS = (
    "source_name",
    "source_url",
    "primary_source",
    "source_urls",
    "dedupe_confidence",
    "external_id",
    "tribunal",
    "tribunal_code",
    "sale_venue_type",
    "sale_legal_framework",
    "sale_verification_status",
    "sale_procedure",
    "department",
    "city",
    "address",
    "postal_code",
    "property_type",
    "title",
    "description",
    "surface_m2",
    "habitable_surface_m2",
    "land_surface_m2",
    "carrez_surface_m2",
    "app_surface_m2",
    "app_surface_kind",
    "surface_scope",
    "surface_source",
    "surface_confidence",
    "surface_evidence",
    "rooms_count",
    "bedrooms_count",
    "bathrooms_count",
    "parking_count",
    "has_garden",
    "has_terrace",
    "has_garage",
    "has_pool",
    "has_air_conditioning",
    "has_double_glazing",
    "starting_price_eur",
    "sale_date",
    "visit_dates",
    "lawyer_name",
    "lawyer_contact",
    "status",
    "adjudication_price_eur",
    "documents",
    "latitude",
    "longitude",
    "occupancy_status",
    "risk_notes",
    "investment_score",
    "investment_summary",
    "score_version",
    "score_confidence",
    "score_factors",
    "premium_readiness_score",
    "premium_readiness_status",
    "premium_readiness_policy_version",
    "premium_readiness_factors",
    "premium_readiness_blockers",
    "premium_readiness_missing_fields",
    "premium_readiness_evaluated_at",
    "quality_flags",
    "raw_text",
    "raw_payload",
    "observations",
    "content_hash",
    "last_run_id",
)


PROPERTY_COLUMNS = (
    "source_url",
    "source_name",
    "primary_source",
    "source_urls",
    "external_id",
    "department",
    "city",
    "postal_code",
    "address",
    "property_type",
    "title",
    "description",
    "surface_m2",
    "habitable_surface_m2",
    "land_surface_m2",
    "carrez_surface_m2",
    "app_surface_m2",
    "app_surface_kind",
    "surface_scope",
    "surface_source",
    "surface_confidence",
    "surface_evidence",
    "rooms_count",
    "bedrooms_count",
    "bathrooms_count",
    "parking_count",
    "has_garden",
    "has_terrace",
    "has_garage",
    "has_pool",
    "has_air_conditioning",
    "has_double_glazing",
    "occupancy_status",
    "latitude",
    "longitude",
    "raw_payload",
)


JUDICIAL_SALE_COLUMNS = (
    "source_url",
    "property_source_url",
    "source_name",
    "primary_source",
    "source_urls",
    "external_id",
    "tribunal",
    "tribunal_code",
    "starting_price_eur",
    "sale_date",
    "visit_dates",
    "status",
    "adjudication_price_eur",
    "source_lawyer_name",
    "source_lawyer_contact",
    "documents_count",
    "investment_score",
    "investment_summary",
    "score_version",
    "score_confidence",
    "score_factors",
    "quality_flags",
    "content_hash",
    "last_run_id",
    "raw_payload",
)


LLM_BACKFILL_SALE_SELECT = ",".join(
    (
        "id",
        *UPSERT_COLUMNS,
        "first_seen_at",
        "last_seen_at",
        "created_at",
        "updated_at",
    )
)


DEDUPLICATION_SALE_SELECT = ",".join(
    (
        "id",
        *UPSERT_COLUMNS,
        "first_seen_at",
        "last_seen_at",
        "created_at",
        "updated_at",
    )
)
