/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesNewRouteImport } from './routes/sales.new'
import { Route as SalesIdRouteImport } from './routes/sales.$id'

const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesRoute,
} as any)
const SalesIdRoute = SalesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRouteWithChildren
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales': typeof SalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRouteWithChildren
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/favorites'
    | '/login'
    | '/map'
    | '/reset-password'
    | '/sales'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/favorites'
    | '/login'
    | '/map'
    | '/reset-password'
    | '/sales/$id'
    | '/sales/new'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/favorites'
    | '/login'
    | '/map'
    | '/reset-password'
    | '/sales'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesRoute: typeof SalesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/$id': {
      id: '/sales/$id'
      path: '/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof SalesIdRouteImport
      parentRoute: typeof SalesRoute
    }
  }
}

interface SalesRouteChildren {
  SalesIdRoute: typeof SalesIdRoute
  SalesNewRoute: typeof SalesNewRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesIdRoute: SalesIdRoute,
  SalesNewRoute: SalesNewRoute,
  SalesIndexRoute: SalesIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesRoute: SalesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
