begin;

-- Subscription/feature layer for the offer matrix.
-- Stripe will later write to this table; until then every user falls back to
-- the free "decouverte" plan in application code.
create table if not exists public.user_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_code text not null default 'decouverte' check (plan_code in ('decouverte', 'analyse')),
  status text not null default 'active' check (
    status in ('trialing', 'active', 'past_due', 'paused', 'cancelled', 'expired')
  ),
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  current_period_end timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.user_subscriptions is
  'ImmoJudis subscription entitlements. Source of truth for Decouverte/Analyse feature access; not source-site contact data.';

create table if not exists public.saved_property_reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  sale_id uuid not null references public.auction_sales(id) on delete cascade,
  report_kind text not null default 'opportunity' check (
    report_kind in ('opportunity', 'market', 'bid_ceiling')
  ),
  title text not null,
  user_notes text,
  report_snapshot jsonb not null default '{}'::jsonb,
  market_snapshot jsonb not null default '{}'::jsonb,
  environmental_snapshot jsonb,
  ceiling_snapshot jsonb not null default '{}'::jsonb,
  export_count integer not null default 0 check (export_count >= 0),
  last_exported_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, sale_id, report_kind)
);

comment on table public.saved_property_reports is
  'User-owned opportunity reports generated by ImmoJudis for judicial-sale analysis, PDF export and report editing features.';

create table if not exists public.property_report_exports (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.saved_property_reports(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  export_format text not null default 'pdf' check (export_format in ('pdf')),
  created_at timestamptz not null default now()
);

comment on table public.property_report_exports is
  'Audit trail for report exports and plan quota enforcement.';

create index if not exists user_subscriptions_plan_status_idx
  on public.user_subscriptions (plan_code, status);

create index if not exists saved_property_reports_user_created_idx
  on public.saved_property_reports (user_id, created_at desc);

create index if not exists saved_property_reports_sale_idx
  on public.saved_property_reports (sale_id);

create index if not exists property_report_exports_user_created_idx
  on public.property_report_exports (user_id, created_at desc);

create index if not exists property_report_exports_report_idx
  on public.property_report_exports (report_id);

alter table public.user_subscriptions enable row level security;
alter table public.saved_property_reports enable row level security;
alter table public.property_report_exports enable row level security;

revoke all on table public.user_subscriptions from anon, authenticated;
revoke all on table public.saved_property_reports from anon, authenticated;
revoke all on table public.property_report_exports from anon, authenticated;

grant select on table public.user_subscriptions to authenticated;
grant select, insert, update, delete on table public.saved_property_reports to authenticated;
grant select, insert on table public.property_report_exports to authenticated;

grant select, insert, update, delete on table public.user_subscriptions to service_role;
grant select, insert, update, delete on table public.saved_property_reports to service_role;
grant select, insert, update, delete on table public.property_report_exports to service_role;

drop trigger if exists immojudis_user_subscriptions_updated_at
on public.user_subscriptions;
create trigger immojudis_user_subscriptions_updated_at
before update on public.user_subscriptions
for each row
execute function app_private.set_user_profiles_updated_at();

drop trigger if exists immojudis_saved_property_reports_updated_at
on public.saved_property_reports;
create trigger immojudis_saved_property_reports_updated_at
before update on public.saved_property_reports
for each row
execute function app_private.set_user_profiles_updated_at();

drop policy if exists user_subscriptions_select_authorized
on public.user_subscriptions;
create policy user_subscriptions_select_authorized
on public.user_subscriptions
for select
to authenticated
using (
  user_id = (select auth.uid())
  or public.is_admin()
);

drop policy if exists user_subscriptions_admin_insert
on public.user_subscriptions;
create policy user_subscriptions_admin_insert
on public.user_subscriptions
for insert
to authenticated
with check (public.is_admin());

drop policy if exists user_subscriptions_admin_update
on public.user_subscriptions;
create policy user_subscriptions_admin_update
on public.user_subscriptions
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists user_subscriptions_admin_delete
on public.user_subscriptions;
create policy user_subscriptions_admin_delete
on public.user_subscriptions
for delete
to authenticated
using (public.is_admin());

drop policy if exists saved_property_reports_select_authorized
on public.saved_property_reports;
create policy saved_property_reports_select_authorized
on public.saved_property_reports
for select
to authenticated
using (
  user_id = (select auth.uid())
  or public.is_admin()
);

drop policy if exists saved_property_reports_insert_own
on public.saved_property_reports;
create policy saved_property_reports_insert_own
on public.saved_property_reports
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists saved_property_reports_update_own
on public.saved_property_reports;
create policy saved_property_reports_update_own
on public.saved_property_reports
for update
to authenticated
using (
  user_id = (select auth.uid())
  or public.is_admin()
)
with check (
  user_id = (select auth.uid())
  or public.is_admin()
);

drop policy if exists saved_property_reports_delete_own
on public.saved_property_reports;
create policy saved_property_reports_delete_own
on public.saved_property_reports
for delete
to authenticated
using (
  user_id = (select auth.uid())
  or public.is_admin()
);

drop policy if exists property_report_exports_select_authorized
on public.property_report_exports;
create policy property_report_exports_select_authorized
on public.property_report_exports
for select
to authenticated
using (
  user_id = (select auth.uid())
  or public.is_admin()
);

drop policy if exists property_report_exports_insert_own
on public.property_report_exports;
create policy property_report_exports_insert_own
on public.property_report_exports
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.saved_property_reports report
    where report.id = report_id
      and report.user_id = (select auth.uid())
  )
);

notify pgrst, 'reload schema';

commit;
