begin;

-- Version aligned with the migration recorded on the production project.

create table public.information_agent_email_templates (
  id uuid primary key default gen_random_uuid(),
  revision bigint generated by default as identity unique,
  name text not null default 'Demande d’informations' check (
    char_length(name) between 3 and 120
  ),
  status text not null default 'draft' check (
    status in ('draft', 'published', 'archived')
  ),
  subject_template text not null check (
    char_length(subject_template) between 3 and 200
    and subject_template !~ E'[\\r\\n]'
  ),
  blocks jsonb not null check (
    jsonb_typeof(blocks) = 'array'
    and jsonb_array_length(blocks) between 1 and 12
    and pg_column_size(blocks) <= 32768
  ),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  published_by uuid references auth.users(id) on delete set null,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (status = 'published' and published_at is not null)
    or status <> 'published'
  )
);

create unique index information_agent_email_templates_one_published_idx
  on public.information_agent_email_templates ((status))
  where status = 'published';
create unique index information_agent_email_templates_one_draft_idx
  on public.information_agent_email_templates ((status))
  where status = 'draft';
create index information_agent_email_templates_history_idx
  on public.information_agent_email_templates (revision desc, created_at desc);

alter table public.information_agent_email_templates enable row level security;
revoke all on table public.information_agent_email_templates from public, anon, authenticated;
grant select, insert, update on table public.information_agent_email_templates to service_role;
revoke all on sequence public.information_agent_email_templates_revision_seq
from public, anon, authenticated;
grant usage, select on sequence public.information_agent_email_templates_revision_seq
to service_role;

create trigger information_agent_email_templates_updated_at
before update on public.information_agent_email_templates
for each row execute function app_private.set_user_profiles_updated_at();

insert into public.information_agent_email_templates (
  name,
  status,
  subject_template,
  blocks,
  published_at
)
values (
  'Demande d’informations — modèle initial',
  'published',
  'Demande d’informations — {{sale_title}} — audience du {{hearing_date}}',
  jsonb_build_array(
    jsonb_build_object(
      'id', 'greeting',
      'kind', 'dynamic',
      'label', 'Formule d’appel',
      'content', 'Bonjour {{recipient_name}},'
    ),
    jsonb_build_object(
      'id', 'identity',
      'kind', 'fixed',
      'label', 'Présentation ImmoJudis',
      'content', 'ImmoJudis est un service indépendant d’analyse des ventes immobilières judiciaires. Nous vous contactons à la demande d’un utilisateur intéressé par cette vente, après validation explicite de sa demande.'
    ),
    jsonb_build_object(
      'id', 'sale_details',
      'kind', 'dynamic',
      'label', 'Informations de la vente',
      'content', E'Référence de l’annonce : {{sale_reference}}\nDate annoncée : {{hearing_date}}\nMise à prix annoncée : {{starting_price}}'
    ),
    jsonb_build_object(
      'id', 'request_intro',
      'kind', 'fixed',
      'label', 'Introduction de la demande',
      'content', 'Afin de permettre une étude du dossier sur la base d’informations fiables et à jour, pourriez-vous nous préciser les éléments suivants ?'
    ),
    jsonb_build_object(
      'id', 'questions',
      'kind', 'dynamic',
      'label', 'Questions adaptées à l’annonce',
      'content', '{{questions}}'
    ),
    jsonb_build_object(
      'id', 'reply_instructions',
      'kind', 'fixed',
      'label', 'Consignes de réponse',
      'content', 'Vous pouvez répondre directement à cet email et y joindre les documents ou photographies que vous êtes autorisé à communiquer. Votre réponse sera conservée dans un espace privé, analysée avec traçabilité puis contrôlée avant toute intégration aux données ImmoJudis.'
    ),
    jsonb_build_object(
      'id', 'closing',
      'kind', 'fixed',
      'label', 'Conclusion et signature',
      'content', E'Nous vous remercions par avance pour votre aide et restons à votre disposition si vous souhaitez préciser le périmètre de cette demande.\n\nCordialement,\nL’équipe ImmoJudis'
    )
  ),
  statement_timestamp()
);

create or replace function public.publish_information_agent_email_template(
  p_template_id uuid,
  p_admin_id uuid
)
returns public.information_agent_email_templates
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_template public.information_agent_email_templates%rowtype;
begin
  if not exists (
    select 1
    from public.user_profiles profile
    where profile.user_id = p_admin_id
      and profile.user_role = 'admin'
  ) then
    raise exception using errcode = '42501', message = 'Administrator access required.';
  end if;

  select * into v_template
  from public.information_agent_email_templates template
  where template.id = p_template_id
  for update;

  if v_template.id is null or v_template.status <> 'draft' then
    raise exception using errcode = '55000', message = 'A draft template is required.';
  end if;

  update public.information_agent_email_templates
  set status = 'archived',
      updated_by = p_admin_id,
      updated_at = statement_timestamp()
  where status = 'published';

  update public.information_agent_email_templates
  set status = 'published',
      published_by = p_admin_id,
      published_at = statement_timestamp(),
      updated_by = p_admin_id,
      updated_at = statement_timestamp()
  where id = p_template_id
  returning * into v_template;

  return v_template;
end;
$$;

revoke all on function public.publish_information_agent_email_template(uuid, uuid)
from public, anon, authenticated;
grant execute on function public.publish_information_agent_email_template(uuid, uuid)
to service_role;

commit;
