begin;

-- Sensitive referral workflow columns are server-owned. User-facing code reads
-- an explicit projection through the service role and always filters by the
-- authenticated requester id.
revoke select on table public.lawyer_referral_requests from authenticated;

-- Queue state, monitor snapshots, matches and delivery records are generated by
-- trusted workers. End users can only read their rows and acknowledge events.
revoke insert on table public.data_refresh_requests from authenticated;

revoke insert, update, delete on table public.user_sale_watch_snapshots from authenticated;
grant select on table public.user_sale_watch_snapshots to authenticated;

revoke insert, update, delete on table public.user_sale_change_events from authenticated;
grant select on table public.user_sale_change_events to authenticated;
grant update (read_at, dismissed_at) on table public.user_sale_change_events to authenticated;

revoke insert, update, delete on table public.user_alert_matches from authenticated;
grant select on table public.user_alert_matches to authenticated;

-- The access-tier introduction copied active Stripe access into a permanent
-- manual tier. A subscription row remains the source of truth for that cohort,
-- including its current_period_end, while genuine manual grants without any
-- subscription history remain untouched.
update public.user_profiles profile
set account_tier = 'free'
where profile.user_role <> 'admin'
  and profile.account_tier = 'premium'
  and exists (
    select 1
    from public.user_subscriptions subscription
    where subscription.user_id = profile.user_id
      and subscription.plan_code = 'analyse'
  );

-- Keep every finite user resource quota atomic. session_user identifies the
-- PostgREST authenticator even though this SECURITY DEFINER function executes
-- as its owner; direct operator SQL remains the only explicit bypass.
create or replace function app_private.enforce_finite_resource_quota()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_count bigint;
  quota_key text;
  target_user_id uuid;
begin
  if tg_table_name = 'sale_workspace_collaborators' then
    target_user_id := new.owner_id;
  else
    target_user_id := new.user_id;
  end if;

  if target_user_id is null then
    raise exception using errcode = '23514', message = 'Quota owner is required.';
  end if;

  if session_user not in ('postgres', 'supabase_admin')
    and not app_private.has_active_analysis_access(target_user_id)
    and not coalesce(public.is_admin(), false) then
    raise exception using errcode = '42501', message = 'Analyse access is required.';
  end if;

  quota_key := tg_table_name || ':' || target_user_id::text;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(quota_key, 0));

  case tg_table_name
    when 'user_api_keys' then
      if new.revoked_at is not null then return new; end if;
      select count(*) into current_count
      from public.user_api_keys item
      where item.user_id = new.user_id
        and item.revoked_at is null
        and item.id <> new.id;
      if current_count >= 2 then
        raise exception using errcode = 'P0001', message = 'Quota de 2 clés API actives atteint.';
      end if;
    when 'user_watched_zones' then
      if not new.is_active then return new; end if;
      select count(*) into current_count
      from public.user_watched_zones item
      where item.user_id = new.user_id
        and item.is_active
        and item.id <> new.id;
      if current_count >= 25 then
        raise exception using errcode = 'P0001', message = 'Quota de 25 zones surveillées atteint.';
      end if;
    when 'user_alerts' then
      if not new.is_active then return new; end if;
      select count(*) into current_count
      from public.user_alerts item
      where item.user_id = new.user_id
        and item.is_active
        and item.id <> new.id;
      if current_count >= 25 then
        raise exception using errcode = 'P0001', message = 'Quota de 25 alertes actives atteint.';
      end if;
    when 'user_sale_analysis_sets' then
      if new.is_archived then return new; end if;
      select count(*) into current_count
      from public.user_sale_analysis_sets item
      where item.user_id = new.user_id
        and not item.is_archived
        and item.id <> new.id;
      if current_count >= 20 then
        raise exception using errcode = 'P0001', message = 'Quota de 20 analyses multi-biens atteint.';
      end if;
    when 'user_sale_analysis_items' then
      quota_key := tg_table_name || ':' || new.analysis_set_id::text;
      perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(quota_key, 0));
      select count(*) into current_count
      from public.user_sale_analysis_items item
      where item.analysis_set_id = new.analysis_set_id
        and item.id <> new.id;
      if current_count >= 12 then
        raise exception using errcode = 'P0001', message = 'Quota de 12 biens par analyse atteint.';
      end if;
    when 'sale_workspace_collaborators' then
      if new.status = 'revoked' then return new; end if;
      quota_key := tg_table_name || ':' || new.workspace_id::text;
      perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(quota_key, 0));
      select count(*) into current_count
      from public.sale_workspace_collaborators item
      where item.workspace_id = new.workspace_id
        and item.status <> 'revoked'
        and item.id <> new.id;
      if current_count >= 25 then
        raise exception using errcode = 'P0001', message = 'Quota de 25 collaborateurs par dossier atteint.';
      end if;
    else
      raise exception using errcode = '0A000', message = 'Unsupported quota trigger table.';
  end case;

  return new;
end;
$$;

drop trigger if exists enforce_user_alerts_quota on public.user_alerts;
create trigger enforce_user_alerts_quota
before insert or update of user_id, is_active on public.user_alerts
for each row execute function app_private.enforce_finite_resource_quota();

-- The public preview accepts only bounded inputs. Anonymous callers cannot use
-- protected attributes as a yes/no oracle even though the result projection is
-- intentionally small.
create or replace function public.search_auction_sales_preview(
  p_departments text[] default null,
  p_city text default null,
  p_postal_code text default null,
  p_tribunal text default null,
  p_keywords text[] default null,
  p_property_types text[] default null,
  p_min_price numeric default null,
  p_max_price numeric default null,
  p_min_surface numeric default null,
  p_max_surface numeric default null,
  p_min_bedrooms integer default null,
  p_min_bathrooms integer default null,
  p_occupancy_status text default null,
  p_min_score numeric default null,
  p_statuses text[] default null,
  p_north double precision default null,
  p_south double precision default null,
  p_east double precision default null,
  p_west double precision default null,
  p_sort text default 'score_desc',
  p_limit integer default 24,
  p_offset integer default 0
)
returns table (
  id uuid,
  starting_price_eur numeric,
  total_count bigint
)
language plpgsql
stable
security invoker
set search_path = ''
as $$
begin
  if coalesce(cardinality(p_departments), 0) > 8
    or coalesce(cardinality(p_keywords), 0) > 5
    or coalesce(cardinality(p_property_types), 0) > 8
    or coalesce(cardinality(p_statuses), 0) > 4
    or coalesce((select max(length(item.value)) from unnest(p_departments) as item(value)), 0) > 80
    or coalesce((select max(length(item.value)) from unnest(p_keywords) as item(value)), 0) > 80
    or coalesce((select max(length(item.value)) from unnest(p_property_types) as item(value)), 0) > 80
    or coalesce((select max(length(item.value)) from unnest(p_statuses) as item(value)), 0) > 40
    or length(coalesce(p_city, '')) > 120
    or length(coalesce(p_postal_code, '')) > 16
    or length(coalesce(p_tribunal, '')) > 160
    or length(coalesce(p_sort, '')) > 32
    or coalesce(p_limit, 24) < 1
    or coalesce(p_limit, 24) > 100
    or coalesce(p_offset, 0) < 0
    or coalesce(p_offset, 0) > 10000 then
    raise exception using errcode = '22023', message = 'Invalid or oversized preview search parameters.';
  end if;

  if current_user = 'anon' and (
    p_min_surface is not null
    or p_max_surface is not null
    or p_min_bedrooms is not null
    or p_min_bathrooms is not null
    or p_occupancy_status is not null
    or p_min_score is not null
    or p_north is not null
    or p_south is not null
    or p_east is not null
    or p_west is not null
  ) then
    raise exception using errcode = '42501', message = 'Protected preview filters require authentication.';
  end if;

  return query
  select *
  from app_private.search_auction_sales_preview(
    p_departments => p_departments,
    p_city => p_city,
    p_postal_code => p_postal_code,
    p_tribunal => p_tribunal,
    p_keywords => p_keywords,
    p_property_types => p_property_types,
    p_min_price => p_min_price,
    p_max_price => p_max_price,
    p_min_surface => p_min_surface,
    p_max_surface => p_max_surface,
    p_min_bedrooms => p_min_bedrooms,
    p_min_bathrooms => p_min_bathrooms,
    p_occupancy_status => p_occupancy_status,
    p_min_score => p_min_score,
    p_statuses => p_statuses,
    p_north => p_north,
    p_south => p_south,
    p_east => p_east,
    p_west => p_west,
    p_sort => p_sort,
    p_limit => p_limit,
    p_offset => p_offset
  );
end;
$$;

revoke all on function public.search_auction_sales_preview from public;
grant execute on function public.search_auction_sales_preview to anon, authenticated, service_role;

-- Durable, deduplicated operational alerts. The health evaluator records
-- cron failures, stale jobs, webhook failures and refresh backlog age.
create table if not exists public.operational_alerts (
  alert_key text primary key,
  category text not null check (category in ('cron', 'webhook', 'import', 'refresh_queue')),
  severity text not null check (severity in ('warning', 'critical')),
  status text not null default 'open' check (status in ('open', 'resolved')),
  details jsonb not null default '{}'::jsonb check (pg_column_size(details) <= 32768),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz
);

alter table public.operational_alerts enable row level security;
revoke all on table public.operational_alerts from public, anon, authenticated;
grant select, insert, update, delete on table public.operational_alerts to service_role;

create or replace function app_private.evaluate_operational_health(
  p_now timestamptz default statement_timestamp()
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  stale_cron_count integer;
  webhook_failure_count integer;
  webhook_stuck_count integer;
  import_failure_count integer;
  import_stuck_count integer;
  import_backlog_count integer;
  oldest_import_age_seconds integer;
  refresh_backlog_count integer;
  oldest_refresh_age_seconds integer;
  open_alert_count integer;
begin
  select count(*)::integer into stale_cron_count
  from (
    values
      ('smart-alerts', interval '30 hours'),
      ('alert-notifications', interval '30 hours'),
      ('sale-change-monitor', interval '30 hours'),
      ('precompute-valuations', interval '30 hours'),
      ('data-retention', interval '8 days')
  ) expected(job_name, max_age)
  where not exists (
    select 1
    from public.operational_job_runs run
    where run.job_name = expected.job_name
      and run.status = 'success'
      and run.finished_at >= p_now - expected.max_age
  );

  select count(*)::integer into webhook_failure_count
  from public.stripe_webhook_events
  where processing_status = 'failed'
    and updated_at >= p_now - interval '1 hour';

  select count(*)::integer into webhook_stuck_count
  from public.stripe_webhook_events
  where processing_status = 'processing'
    and updated_at < p_now - interval '15 minutes';

  select count(*)::integer into import_failure_count
  from public.auction_runs
  where status = 'failed'
    and coalesce(finished_at, updated_at, created_at) >= p_now - interval '1 hour';

  select count(*)::integer into import_stuck_count
  from public.auction_runs
  where status = 'running'
    and started_at < p_now - interval '3 hours';

  select
    count(*)::integer,
    coalesce(max(extract(epoch from (p_now - created_at)))::integer, 0)
  into import_backlog_count, oldest_import_age_seconds
  from public.auction_runs
  where status = 'queued';

  select
    count(*)::integer,
    coalesce(max(extract(epoch from (p_now - created_at)))::integer, 0)
  into refresh_backlog_count, oldest_refresh_age_seconds
  from public.data_refresh_requests
  where status in ('queued', 'running');

  if stale_cron_count > 0 then
    insert into public.operational_alerts (alert_key, category, severity, details, last_seen_at)
    values ('cron.stale', 'cron', 'critical', jsonb_build_object('stale_jobs', stale_cron_count), p_now)
    on conflict (alert_key) do update set
      severity = excluded.severity, status = 'open', details = excluded.details,
      last_seen_at = excluded.last_seen_at, resolved_at = null;
  else
    update public.operational_alerts set status = 'resolved', resolved_at = p_now
    where alert_key = 'cron.stale' and status = 'open';
  end if;

  if webhook_failure_count > 0 or webhook_stuck_count > 0 then
    insert into public.operational_alerts (alert_key, category, severity, details, last_seen_at)
    values (
      'stripe.webhook.unhealthy', 'webhook', 'critical',
      jsonb_build_object('failed_last_hour', webhook_failure_count, 'stuck_processing', webhook_stuck_count),
      p_now
    )
    on conflict (alert_key) do update set
      severity = excluded.severity, status = 'open', details = excluded.details,
      last_seen_at = excluded.last_seen_at, resolved_at = null;
  else
    update public.operational_alerts set status = 'resolved', resolved_at = p_now
    where alert_key = 'stripe.webhook.unhealthy' and status = 'open';
  end if;

  if import_failure_count > 0 or import_stuck_count > 0 or oldest_import_age_seconds > 1800 then
    insert into public.operational_alerts (alert_key, category, severity, details, last_seen_at)
    values (
      'pipeline.import.unhealthy', 'import',
      case when import_stuck_count > 0 or oldest_import_age_seconds > 7200
        then 'critical' else 'warning' end,
      jsonb_build_object(
        'failed_last_hour', import_failure_count,
        'stuck_running', import_stuck_count,
        'queued', import_backlog_count,
        'oldest_queued_age_seconds', oldest_import_age_seconds
      ),
      p_now
    )
    on conflict (alert_key) do update set
      severity = excluded.severity, status = 'open', details = excluded.details,
      last_seen_at = excluded.last_seen_at, resolved_at = null;
  else
    update public.operational_alerts set status = 'resolved', resolved_at = p_now
    where alert_key = 'pipeline.import.unhealthy' and status = 'open';
  end if;

  if oldest_refresh_age_seconds > 1800 then
    insert into public.operational_alerts (alert_key, category, severity, details, last_seen_at)
    values (
      'refresh_queue.stale', 'refresh_queue',
      case when oldest_refresh_age_seconds > 7200 then 'critical' else 'warning' end,
      jsonb_build_object('backlog', refresh_backlog_count, 'oldest_age_seconds', oldest_refresh_age_seconds),
      p_now
    )
    on conflict (alert_key) do update set
      severity = excluded.severity, status = 'open', details = excluded.details,
      last_seen_at = excluded.last_seen_at, resolved_at = null;
  else
    update public.operational_alerts set status = 'resolved', resolved_at = p_now
    where alert_key = 'refresh_queue.stale' and status = 'open';
  end if;

  select count(*)::integer into open_alert_count
  from public.operational_alerts where status = 'open';

  return jsonb_build_object(
    'ok', open_alert_count = 0,
    'open_alerts', open_alert_count,
    'stale_crons', stale_cron_count,
    'webhook_failures', webhook_failure_count,
    'webhook_stuck', webhook_stuck_count,
    'import_failures', import_failure_count,
    'import_stuck', import_stuck_count,
    'import_backlog', import_backlog_count,
    'oldest_import_age_seconds', oldest_import_age_seconds,
    'refresh_backlog', refresh_backlog_count,
    'oldest_refresh_age_seconds', oldest_refresh_age_seconds
  );
end;
$$;

revoke all on function app_private.evaluate_operational_health(timestamptz)
from public, anon, authenticated;
grant execute on function app_private.evaluate_operational_health(timestamptz) to service_role;

create or replace function public.evaluate_operational_health(
  p_now timestamptz default statement_timestamp()
)
returns jsonb
language sql
security definer
set search_path = ''
as $$
  select app_private.evaluate_operational_health(p_now);
$$;

revoke all on function public.evaluate_operational_health(timestamptz)
from public, anon, authenticated;
grant execute on function public.evaluate_operational_health(timestamptz) to service_role;

notify pgrst, 'reload schema';

commit;
